<?php $slides = $this->getDatasets(); ?>
<div class="slider-stacked" id="header-slider-stacked">
    <div class="slider-wrapper">
        <?php foreach ($slides as $slide) : ?>
            <div class="stacked-slide">
                <a href="<?php echo $slide->getLink() ?>">
                    <img alt="" src="<?php echo $slide->getImageUrl() ?>"/>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
    <!-- Add Pagination -->
    <div class="swiper-pagination"></div>
</div>